Fix compatibility with Java 17 (#4962)
## Summary

This PR removes `MaxPermSize` flag from `android/gradle.properties`,
because is removed since Java 17
https://docs.oracle.com/en/java/javase/17/docs/specs/man/java.html#removed-java-options.
The next React Native version will require Java 17.

## Error

```
➜  android git:(main) java --version
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Homebrew (build 17.0.8+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.8+0, mixed mode, sharing)
```

```
➜  android git:(main) ./gradlew :spotlessApply
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

Unrecognized VM option 'MaxPermSize=512m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

## Test plan

```
cd android && ./gradlew :spotlessApply
```