Fix chrome debugger for android (#2795)
## Description

Layout animated provided many changes, one of the effects is that Reanimated always tries to load the native module, but this breaks the chrome debugger on Android, unfortunately. I detected when chrome debugger is enabled based on React Native code: [source](https://github.com/facebook/react-native/blob/v0.67.0-rc.6/ReactAndroid/src/main/java/com/facebook/react/modules/blob/BlobCollector.java#L25-L26)
```js
// When debugging in chrome the JS context is not available.
if (jsContext.get() != 0) {
```
ant then I don't load the native reanimated module.

Crash:
```
E/AndroidRuntime: FATAL EXCEPTION: mqt_js
    Process: com.swmansion.reanimated.example, PID: 3681
    java.lang.AssertionError: No source URL loaded, have you initialised the instance?
        at com.facebook.infer.annotation.Assertions.assertNotNull(Assertions.java:19)
        at com.facebook.react.modules.debug.SourceCodeModule.getTypedExportedConstants(SourceCodeModule.java:39)
        at com.facebook.fbreact.specs.NativeSourceCodeSpec.getConstants(NativeSourceCodeSpec.java:38)
        at com.facebook.react.bridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:142)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:923)
I/Process: Sending signal. PID: 3681 SIG: 9
```

Fixes #2671 

Related threads:
- https://github.com/expo/expo/issues/10284
- https://github.com/expo/expo/pull/10383
- https://github.com/facebook/react-native/issues/28844